[package]
name = "move_to_target"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
rand = "0.8"

[features]
default = ["dynamic"]

dynamic = ["bevy/dynamic"]
